CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_BR.BR_SUPPLIER_PRODUCT_METRICS (
    SUPPLIERID VARCHAR,
    PRODUCTID VARCHAR,
    TOTAL_SALES_QUANTITY NUMBER(38,0),
    AVG_INVENTORY_UNITS NUMBER(38,6),
    AVG_LANDED_COST_PER_UNIT NUMBER(38,6),
    AVG_OTIF_RATE NUMBER(38,6),
    AVG_LAST_MILE_EFFICIENCY NUMBER(38,6),
    AVG_CARBON_FOOTPRINT_EST NUMBER(38,6),
    AVG_STOCKOUT_RISK_SCORE NUMBER(38,6),
    AVG_ORDER_TO_CASH_CYCLE_DAYS NUMBER(38,6),
    AVG_CARRIER_LEAD_TIME_VARIANCE NUMBER(38,6),
    RETURN_TO_SALES_RATIO NUMBER(38,6),
    AVG_GMROI NUMBER(38,6)
);

MERGE INTO AI_ETL.AI_ETL_BR.BR_SUPPLIER_PRODUCT_METRICS AS T
USING (
    SELECT
        SUPPLIERID,
        PRODUCTID,
        SUM(SALES_QUANTITY) AS TOTAL_SALES_QUANTITY,
        AVG(INVENTORY_UNITS) AS AVG_INVENTORY_UNITS,
        AVG(LANDED_COST_PER_UNIT) AS AVG_LANDED_COST_PER_UNIT,
        AVG(OTIF_FLAG) AS AVG_OTIF_RATE,
        AVG(LAST_MILE_EFFICIENCY) AS AVG_LAST_MILE_EFFICIENCY,
        AVG(CARBON_FOOTPRINT_EST) AS AVG_CARBON_FOOTPRINT_EST,
        AVG(STOCKOUT_RISK_SCORE) AS AVG_STOCKOUT_RISK_SCORE,
        AVG(ORDER_TO_CASH_CYCLE_DAYS) AS AVG_ORDER_TO_CASH_CYCLE_DAYS,
        AVG(CARRIER_LEAD_TIME_VARIANCE) AS AVG_CARRIER_LEAD_TIME_VARIANCE,
        CASE
            WHEN SUM(SALES_QUANTITY) IS NULL OR SUM(SALES_QUANTITY) = 0 THEN NULL
            ELSE SUM(RETURN_INDICATOR) / SUM(SALES_QUANTITY)
        END AS RETURN_TO_SALES_RATIO,
        AVG(GMROI) AS AVG_GMROI
    FROM AI_ETL.AI_ETL_WI.TRF_ORDER_SUPPLY_METRICS
    GROUP BY SUPPLIERID, PRODUCTID
) AS S
ON (T.SUPPLIERID = S.SUPPLIERID AND T.PRODUCTID = S.PRODUCTID)
WHEN MATCHED THEN UPDATE SET
    T.TOTAL_SALES_QUANTITY = S.TOTAL_SALES_QUANTITY,
    T.AVG_INVENTORY_UNITS = S.AVG_INVENTORY_UNITS,
    T.AVG_LANDED_COST_PER_UNIT = S.AVG_LANDED_COST_PER_UNIT,
    T.AVG_OTIF_RATE = S.AVG_OTIF_RATE,
    T.AVG_LAST_MILE_EFFICIENCY = S.AVG_LAST_MILE_EFFICIENCY,
    T.AVG_CARBON_FOOTPRINT_EST = S.AVG_CARBON_FOOTPRINT_EST,
    T.AVG_STOCKOUT_RISK_SCORE = S.AVG_STOCKOUT_RISK_SCORE,
    T.AVG_ORDER_TO_CASH_CYCLE_DAYS = S.AVG_ORDER_TO_CASH_CYCLE_DAYS,
    T.AVG_CARRIER_LEAD_TIME_VARIANCE = S.AVG_CARRIER_LEAD_TIME_VARIANCE,
    T.RETURN_TO_SALES_RATIO = S.RETURN_TO_SALES_RATIO,
    T.AVG_GMROI = S.AVG_GMROI
WHEN NOT MATCHED THEN INSERT (
    SUPPLIERID,
    PRODUCTID,
    TOTAL_SALES_QUANTITY,
    AVG_INVENTORY_UNITS,
    AVG_LANDED_COST_PER_UNIT,
    AVG_OTIF_RATE,
    AVG_LAST_MILE_EFFICIENCY,
    AVG_CARBON_FOOTPRINT_EST,
    AVG_STOCKOUT_RISK_SCORE,
    AVG_ORDER_TO_CASH_CYCLE_DAYS,
    AVG_CARRIER_LEAD_TIME_VARIANCE,
    RETURN_TO_SALES_RATIO,
    AVG_GMROI
) VALUES (
    S.SUPPLIERID,
    S.PRODUCTID,
    S.TOTAL_SALES_QUANTITY,
    S.AVG_INVENTORY_UNITS,
    S.AVG_LANDED_COST_PER_UNIT,
    S.AVG_OTIF_RATE,
    S.AVG_LAST_MILE_EFFICIENCY,
    S.AVG_CARBON_FOOTPRINT_EST,
    S.AVG_STOCKOUT_RISK_SCORE,
    S.AVG_ORDER_TO_CASH_CYCLE_DAYS,
    S.AVG_CARRIER_LEAD_TIME_VARIANCE,
    S.RETURN_TO_SALES_RATIO,
    S.AVG_GMROI
);