-- Author: Senior Data Engineer
-- Date: 2024-06-04
-- Description: Staging table for CUSTOMER_DIM with incremental logic

CREATE TABLE IF NOT EXISTS STG_CUSTOMER_DIM LIKE CUSTOMER_DIM;

MERGE INTO STG_CUSTOMER_DIM T
USING CUSTOMER_DIM S
ON T.CUSTOMER_ID = S.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET 
    T.CUSTOMER_NAME = S.CUSTOMER_NAME,
    T.REGION = S.REGION,
    T.CUSTOMER_TYPE = S.CUSTOMER_TYPE
WHEN NOT MATCHED THEN INSERT *;

-- Author: Senior Data Engineer
-- Date: 2024-06-04
-- Description: Staging table for PRODUCT_DIM with incremental logic

CREATE TABLE IF NOT EXISTS STG_PRODUCT_DIM LIKE PRODUCT_DIM;

MERGE INTO STG_PRODUCT_DIM T
USING PRODUCT_DIM S
ON T.PRODUCT_ID = S.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET 
    T.PRODUCT_NAME = S.PRODUCT_NAME,
    T.CATEGORY = S.CATEGORY,
    T.SUPPLIER_ID = S.SUPPLIER_ID
WHEN NOT MATCHED THEN INSERT *;

-- Author: Senior Data Engineer
-- Date: 2024-06-04
-- Description: Staging table for ORDER_DETAILS_NEW with incremental logic

CREATE TABLE IF NOT EXISTS STG_ORDER_DETAILS_NEW LIKE ORDER_DETAILS_NEW;

MERGE INTO STG_ORDER_DETAILS_NEW T
USING ORDER_DETAILS_NEW S
ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED THEN UPDATE SET 
    T.CUSTOMER_ID = S.CUSTOMER_ID,
    T.PRODUCT_ID = S.PRODUCT_ID,
    T.ORDER_DATE = S.ORDER_DATE,
    T.QUANTITY = S.QUANTITY,
    T.PRICE = S.PRICE
WHEN NOT MATCHED THEN INSERT *;

-- Author: Senior Data Engineer
-- Date: 2024-06-04
-- Description: Staging table for SUPPLIER_DIM with incremental logic

CREATE TABLE IF NOT EXISTS STG_SUPPLIER_DIM LIKE SUPPLIER_DIM;

MERGE INTO STG_SUPPLIER_DIM T
USING SUPPLIER_DIM S
ON T.SUPPLIER_ID = S.SUPPLIER_ID
WHEN MATCHED THEN UPDATE SET 
    T.SUPPLIER_NAME = S.SUPPLIER_NAME,
    T.CONTACT = S.CONTACT
WHEN NOT MATCHED THEN INSERT *;