-- Author: Senior Data Engineer
-- Date: 2024-06-04
-- Description: Transformation layer join staging tables to form enriched sales data with regional info filtered by last 2 months

CREATE TABLE IF NOT EXISTS TRF_SALES_ENRICHED AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    C.REGION,
    O.PRODUCT_ID,
    P.CATEGORY,
    S.SUPPLIER_NAME,
    O.ORDER_DATE,
    O.QUANTITY,
    O.PRICE,
    O.QUANTITY * O.PRICE AS SALES_AMOUNT
FROM STG_ORDER_DETAILS_NEW O
JOIN STG_CUSTOMER_DIM C ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN STG_PRODUCT_DIM P ON O.PRODUCT_ID = P.PRODUCT_ID
JOIN STG_SUPPLIER_DIM S ON P.SUPPLIER_ID = S.SUPPLIER_ID
WHERE O.ORDER_DATE >= DATEADD(month, -2, CURRENT_DATE());

MERGE INTO TRF_SALES_ENRICHED T
USING (
    SELECT
        O.ORDER_ID,
        O.CUSTOMER_ID,
        C.REGION,
        O.PRODUCT_ID,
        P.CATEGORY,
        S.SUPPLIER_NAME,
        O.ORDER_DATE,
        O.QUANTITY,
        O.PRICE,
        O.QUANTITY * O.PRICE AS SALES_AMOUNT
    FROM STG_ORDER_DETAILS_NEW O
    JOIN STG_CUSTOMER_DIM C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    JOIN STG_PRODUCT_DIM P ON O.PRODUCT_ID = P.PRODUCT_ID
    JOIN STG_SUPPLIER_DIM S ON P.SUPPLIER_ID = S.SUPPLIER_ID
    WHERE O.ORDER_DATE >= DATEADD(month, -2, CURRENT_DATE())
) S
ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED THEN UPDATE SET
    T.CUSTOMER_ID = S.CUSTOMER_ID,
    T.REGION = S.REGION,
    T.PRODUCT_ID = S.PRODUCT_ID,
    T.CATEGORY = S.CATEGORY,
    T.SUPPLIER_NAME = S.SUPPLIER_NAME,
    T.ORDER_DATE = S.ORDER_DATE,
    T.QUANTITY = S.QUANTITY,
    T.PRICE = S.PRICE,
    T.SALES_AMOUNT = S.SALES_AMOUNT
WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, CUSTOMER_ID, REGION, PRODUCT_ID, CATEGORY, SUPPLIER_NAME, ORDER_DATE, QUANTITY, PRICE, SALES_AMOUNT
)
VALUES (
    S.ORDER_ID, S.CUSTOMER_ID, S.REGION, S.PRODUCT_ID, S.CATEGORY, S.SUPPLIER_NAME, S.ORDER_DATE, S.QUANTITY, S.PRICE, S.SALES_AMOUNT
);