-- Author: Senior Data Engineer
-- Date: 2024-06-04
-- Description: Final KPI table aggregated by region with sales filter and flag for sales > 20000 in last 2 months

CREATE TABLE IF NOT EXISTS KPI_SALES_BY_REGION (
    REGION STRING,
    TOTAL_SALES NUMBER(18,2),
    SALES_FLAG NUMBER(1)
);

MERGE INTO KPI_SALES_BY_REGION T
USING (
    SELECT 
        REGION,
        SUM(SALES_AMOUNT) AS TOTAL_SALES,
        CASE WHEN SUM(SALES_AMOUNT) > 20000 THEN 1 ELSE 0 END AS SALES_FLAG
    FROM TRF_SALES_ENRICHED
    GROUP BY REGION
) S
ON T.REGION = S.REGION
WHEN MATCHED THEN UPDATE SET
    T.TOTAL_SALES = S.TOTAL_SALES,
    T.SALES_FLAG = S.SALES_FLAG
WHEN NOT MATCHED THEN INSERT (
    REGION, TOTAL_SALES, SALES_FLAG
)
VALUES (
    S.REGION, S.TOTAL_SALES, S.SALES_FLAG
);