CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_BR.BR_SUPPLIER_PRODUCT_SUMMARY (
    SUPPLIERID VARCHAR,
    SUPPLIER_NAME VARCHAR,
    PRODUCTID VARCHAR,
    PRODUCT_NAME VARCHAR,
    MODE_OF_SHIPPING VARCHAR,
    TOTAL_SALES_QUANTITY NUMBER(38,0),
    AVG_LANDED_COST_PER_UNIT NUMBER(38,4),
    AVG_LAST_MILE_EFFICIENCY NUMBER(38,4),
    AVG_STOCKOUT_RISK_SCORE NUMBER(38,4),
    AVG_ORDER_TO_CASH_CYCLE_DAYS NUMBER(38,4),
    TOTAL_CARBON_FOOTPRINT_EST NUMBER(38,4),
    OTIF_RATE NUMBER(38,4)
);

MERGE INTO AI_ETL.AI_ETL_BR.BR_SUPPLIER_PRODUCT_SUMMARY T
USING (
    SELECT
        SUPPLIERID,
        SUPPLIER_NAME,
        PRODUCTID,
        PRODUCT_NAME,
        MODE_OF_SHIPPING,
        SUM(COALESCE(SALES_QUANTITY, 0)) AS TOTAL_SALES_QUANTITY,
        AVG(LANDED_COST_PER_UNIT) AS AVG_LANDED_COST_PER_UNIT,
        AVG(LAST_MILE_EFFICIENCY) AS AVG_LAST_MILE_EFFICIENCY,
        AVG(STOCKOUT_RISK_SCORE) AS AVG_STOCKOUT_RISK_SCORE,
        AVG(ORDER_TO_CASH_CYCLE_DAYS) AS AVG_ORDER_TO_CASH_CYCLE_DAYS,
        SUM(COALESCE(CARBON_FOOTPRINT_EST, 0)) AS TOTAL_CARBON_FOOTPRINT_EST,
        AVG(OTIF_FLAG) AS OTIF_RATE
    FROM AI_ETL.AI_ETL_WI.TRF_ORDER_INVENTORY_FACT
    GROUP BY SUPPLIERID, SUPPLIER_NAME, PRODUCTID, PRODUCT_NAME, MODE_OF_SHIPPING
) S
ON (
    T.SUPPLIERID = S.SUPPLIERID
    AND T.PRODUCTID = S.PRODUCTID
    AND COALESCE(T.MODE_OF_SHIPPING, '##NULL##') = COALESCE(S.MODE_OF_SHIPPING, '##NULL##')
)
WHEN MATCHED THEN UPDATE SET
    T.SUPPLIER_NAME = S.SUPPLIER_NAME,
    T.PRODUCT_NAME = S.PRODUCT_NAME,
    T.TOTAL_SALES_QUANTITY = S.TOTAL_SALES_QUANTITY,
    T.AVG_LANDED_COST_PER_UNIT = S.AVG_LANDED_COST_PER_UNIT,
    T.AVG_LAST_MILE_EFFICIENCY = S.AVG_LAST_MILE_EFFICIENCY,
    T.AVG_STOCKOUT_RISK_SCORE = S.AVG_STOCKOUT_RISK_SCORE,
    T.AVG_ORDER_TO_CASH_CYCLE_DAYS = S.AVG_ORDER_TO_CASH_CYCLE_DAYS,
    T.TOTAL_CARBON_FOOTPRINT_EST = S.TOTAL_CARBON_FOOTPRINT_EST,
    T.OTIF_RATE = S.OTIF_RATE
WHEN NOT MATCHED THEN INSERT (
    SUPPLIERID,
    SUPPLIER_NAME,
    PRODUCTID,
    PRODUCT_NAME,
    MODE_OF_SHIPPING,
    TOTAL_SALES_QUANTITY,
    AVG_LANDED_COST_PER_UNIT,
    AVG_LAST_MILE_EFFICIENCY,
    AVG_STOCKOUT_RISK_SCORE,
    AVG_ORDER_TO_CASH_CYCLE_DAYS,
    TOTAL_CARBON_FOOTPRINT_EST,
    OTIF_RATE
)
VALUES (
    S.SUPPLIERID,
    S.SUPPLIER_NAME,
    S.PRODUCTID,
    S.PRODUCT_NAME,
    S.MODE_OF_SHIPPING,
    S.TOTAL_SALES_QUANTITY,
    S.AVG_LANDED_COST_PER_UNIT,
    S.AVG_LAST_MILE_EFFICIENCY,
    S.AVG_STOCKOUT_RISK_SCORE,
    S.AVG_ORDER_TO_CASH_CYCLE_DAYS,
    S.TOTAL_CARBON_FOOTPRINT_EST,
    S.OTIF_RATE
);