CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_STG.STG_CUSTOMER
LIKE AI_ETL.AI_ETL_RAW.CUSTOMER;

INSERT INTO AI_ETL.AI_ETL_STG.DATALOAD (TABLE_NAME, LAST_LOAD_DATE)
SELECT 'CUSTOMER', '1900-01-01'::TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 
    FROM AI_ETL.AI_ETL_STG.DATALOAD 
    WHERE TABLE_NAME = 'CUSTOMER'
);

INSERT OVERWRITE INTO AI_ETL.AI_ETL_STG.STG_CUSTOMER
SELECT *
FROM AI_ETL.AI_ETL_RAW.CUSTOMER;

UPDATE AI_ETL.AI_ETL_STG.DATALOAD
SET LAST_LOAD_DATE = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'CUSTOMER';

CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_STG.STG_INVENTORY
LIKE AI_ETL.AI_ETL_RAW.INVENTORY;

INSERT INTO AI_ETL.AI_ETL_STG.DATALOAD (TABLE_NAME, LAST_LOAD_DATE)
SELECT 'INVENTORY', '1900-01-01'::TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 
    FROM AI_ETL.AI_ETL_STG.DATALOAD 
    WHERE TABLE_NAME = 'INVENTORY'
);

INSERT OVERWRITE INTO AI_ETL.AI_ETL_STG.STG_INVENTORY
SELECT *
FROM AI_ETL.AI_ETL_RAW.INVENTORY;

UPDATE AI_ETL.AI_ETL_STG.DATALOAD
SET LAST_LOAD_DATE = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'INVENTORY';

CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_STG.STG_ORDERS
LIKE AI_ETL.AI_ETL_RAW.ORDERS;

INSERT INTO AI_ETL.AI_ETL_STG.DATALOAD (TABLE_NAME, LAST_LOAD_DATE)
SELECT 'ORDERS', '1900-01-01'::TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 
    FROM AI_ETL.AI_ETL_STG.DATALOAD 
    WHERE TABLE_NAME = 'ORDERS'
);

INSERT OVERWRITE INTO AI_ETL.AI_ETL_STG.STG_ORDERS
SELECT *
FROM AI_ETL.AI_ETL_RAW.ORDERS;

UPDATE AI_ETL.AI_ETL_STG.DATALOAD
SET LAST_LOAD_DATE = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'ORDERS';

CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_STG.STG_PRODUCT
LIKE AI_ETL.AI_ETL_RAW.PRODUCT;

INSERT INTO AI_ETL.AI_ETL_STG.DATALOAD (TABLE_NAME, LAST_LOAD_DATE)
SELECT 'PRODUCT', '1900-01-01'::TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 
    FROM AI_ETL.AI_ETL_STG.DATALOAD 
    WHERE TABLE_NAME = 'PRODUCT'
);

INSERT OVERWRITE INTO AI_ETL.AI_ETL_STG.STG_PRODUCT
SELECT *
FROM AI_ETL.AI_ETL_RAW.PRODUCT;

UPDATE AI_ETL.AI_ETL_STG.DATALOAD
SET LAST_LOAD_DATE = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'PRODUCT';

CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_STG.STG_SUPPLIER
LIKE AI_ETL.AI_ETL_RAW.SUPPLIER;

INSERT INTO AI_ETL.AI_ETL_STG.DATALOAD (TABLE_NAME, LAST_LOAD_DATE)
SELECT 'SUPPLIER', '1900-01-01'::TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 
    FROM AI_ETL.AI_ETL_STG.DATALOAD 
    WHERE TABLE_NAME = 'SUPPLIER'
);

INSERT OVERWRITE INTO AI_ETL.AI_ETL_STG.STG_SUPPLIER
SELECT *
FROM AI_ETL.AI_ETL_RAW.SUPPLIER;

UPDATE AI_ETL.AI_ETL_STG.DATALOAD
SET LAST_LOAD_DATE = CURRENT_TIMESTAMP()
WHERE TABLE_NAME = 'SUPPLIER';