CREATE TABLE IF NOT EXISTS AI_ETL.AI_ETL_BR.BR_SUPPLIER_PRODUCT_METRICS (
    SUPPLIERID VARCHAR,
    PRODUCTID VARCHAR,
    TOTAL_SALES_QUANTITY NUMBER(38,0),
    AVERAGE_OTIF_RATE NUMBER(18,6),
    AVG_LANDED_COST_PER_UNIT NUMBER(18,6),
    AVG_ORDER_TO_CASH_CYCLE_DAYS NUMBER(18,6),
    TOTAL_CARBON_FOOTPRINT NUMBER(18,6),
    TOTAL_SHIPPING_COST NUMBER(18,6),
    TOTAL_STOCKOUT_RISK_SCORE NUMBER(18,6),
    AVG_GMROI NUMBER(18,6)
);

MERGE INTO AI_ETL.AI_ETL_BR.BR_SUPPLIER_PRODUCT_METRICS AS T
USING (
    SELECT
        SUPPLIERID,
        PRODUCTID,
        SUM(SALES_QUANTITY) AS TOTAL_SALES_QUANTITY,
        AVG(OTIF_FLAG) AS AVERAGE_OTIF_RATE,
        AVG(LANDED_COST_PER_UNIT) AS AVG_LANDED_COST_PER_UNIT,
        AVG(ORDER_TO_CASH_CYCLE_DAYS) AS AVG_ORDER_TO_CASH_CYCLE_DAYS,
        SUM(CARBON_FOOTPRINT_EST) AS TOTAL_CARBON_FOOTPRINT,
        SUM(SHIPPING_COST) AS TOTAL_SHIPPING_COST,
        SUM(STOCKOUT_RISK_SCORE) AS TOTAL_STOCKOUT_RISK_SCORE,
        AVG(GMROI) AS AVG_GMROI
    FROM AI_ETL.AI_ETL_WI.TRF_ORDER_SUPPLY_METRICS
    GROUP BY SUPPLIERID, PRODUCTID
) AS S
ON T.SUPPLIERID = S.SUPPLIERID
AND T.PRODUCTID = S.PRODUCTID
WHEN MATCHED THEN UPDATE SET
    T.TOTAL_SALES_QUANTITY = S.TOTAL_SALES_QUANTITY,
    T.AVERAGE_OTIF_RATE = S.AVERAGE_OTIF_RATE,
    T.AVG_LANDED_COST_PER_UNIT = S.AVG_LANDED_COST_PER_UNIT,
    T.AVG_ORDER_TO_CASH_CYCLE_DAYS = S.AVG_ORDER_TO_CASH_CYCLE_DAYS,
    T.TOTAL_CARBON_FOOTPRINT = S.TOTAL_CARBON_FOOTPRINT,
    T.TOTAL_SHIPPING_COST = S.TOTAL_SHIPPING_COST,
    T.TOTAL_STOCKOUT_RISK_SCORE = S.TOTAL_STOCKOUT_RISK_SCORE,
    T.AVG_GMROI = S.AVG_GMROI
WHEN NOT MATCHED THEN INSERT (
    SUPPLIERID,
    PRODUCTID,
    TOTAL_SALES_QUANTITY,
    AVERAGE_OTIF_RATE,
    AVG_LANDED_COST_PER_UNIT,
    AVG_ORDER_TO_CASH_CYCLE_DAYS,
    TOTAL_CARBON_FOOTPRINT,
    TOTAL_SHIPPING_COST,
    TOTAL_STOCKOUT_RISK_SCORE,
    AVG_GMROI
)
VALUES (
    S.SUPPLIERID,
    S.PRODUCTID,
    S.TOTAL_SALES_QUANTITY,
    S.AVERAGE_OTIF_RATE,
    S.AVG_LANDED_COST_PER_UNIT,
    S.AVG_ORDER_TO_CASH_CYCLE_DAYS,
    S.TOTAL_CARBON_FOOTPRINT,
    S.TOTAL_SHIPPING_COST,
    S.TOTAL_STOCKOUT_RISK_SCORE,
    S.AVG_GMROI
);